# Site wide configuration
title: Satriaji Idam's Blog
description : A philomath journey in the cloud world.
locale: en-US
url: https://satriajidam.github.io
og_image: og-image.jpg

# Jekyll configuration
permalink: /:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-paginate

kramdown:
  syntax_highlighter: rouge
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  parse_block_html: true

redcarpet:
  extensions:
    - tables
    - autolink
    - strikethrough
    - space_after_headers
    - with_toc_data
    - fenced_code_blocks

paginate: 10
paginate_path: /page:num/
  
# Site owner
owner:
  name: Satriaji Idam
  avatar: bio-photo.jpg
  bio: >-
    A self-declared philomath from Indonesia who loves programming, the web, devops, 
    and is super passionate about the cloud-native technology.
  email: play.satriajidam@gmail.com
  disqus-shortname: satriaji-idam-blog
  twitter: satriajidam
  facebook:
  google:
    plus:
    analytics: UA-120534368-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: satriajidam
  bitbucket:
  stackoverflow:
  linkedin: satriajidam
  medium: play.satriajidam
  xing:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:
  weibo:
  flickr:
  codepen:

include:
  - .htaccess
  - _pages
exclude:
  - lib
  - config.rb
  - Capfile
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
  - less
  - "*.sublime-project"
  - "*.sublime-workspace"
  - test
  - spec
  - Gruntfile.js
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Front Matter defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      comments: false
      share: false
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      share: true
      related: true
